baseURL: https://mattdancho-portio.netlify.app/
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Matt's Data Science Portfolio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Resume
      url: '#resume'
      weight: 5
    - name: Blog
      url: blog
      weight: 6
  sitemap:
    - name: About me
      url: about
      weight: 1
    - name: Blog
      url: blog
      weight: 2
params:
  blogPageURL: blog
  contactButtonLabel: Join Matt's R Program Today
  contactLink: '#contact'
  copyright: All right reserved copyright © Matt Dancho 2021
  footerLogo: images/site-navigation/logo-matt.png
  formspreeURL: https://formspree.io/f/mdobkekr
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo-matt.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/
      weight: 1
    - icon: fa-youtube-square
      url: https://www.pinterest.com/
      weight: 2
    - icon: fa-twitter-square
      url: https://twitter.com/
      weight: 3
